[package]
name = "app"
version = "1.0.0"
authors = ["SkyeKiwi <hello@skye.kiwi>"]
build = "build.rs"

[dependencies]
skw_ipfs = { path = "../crates/skw-ipfs" }
sgx_types = { path = "../../teaclave-sgx-sdk/sgx_types" }
sgx_urts = { path = "../../teaclave-sgx-sdk/sgx_urts" }
