[workspace]
members = [
    'skw-node',
    'skw-pallets/naming',
    'skw-pallets/secrets',
    'skw-pallets/s-contract',
    'skw-pallets/registry',
    'skw-runtime',
]

exclude = [
    'enclave/app',
    'enclave/enclave',
    'enclave/crates/skw-crypto',
    'enclave/crates/skw-driver',
    'enclave/crates/skw-file',
    'enclave/crates/skw-ipfs',
    'enclave/crates/skw-metadata',
    'enclave/crates/skw-types',
    'enclave/crates/skw-unit-test',
    'enclave/crates/skw-utils',
]
[profile.release]
panic = 'unwind'
