[workspace]
members = [
    'skw-node',
    'skw-pallets/naming',
    'skw-pallets/secrets',
    'skw-pallets/s-contract',
    'skw-pallets/registry',
    'skw-runtime',
]

exclude = [
    'enclave/app',
    'enclave/enclave',
    'enclave/crates/skw-crypto',
    'enclave/crates/skw-driver',
    'enclave/crates/skw-file',
    'enclave/crates/skw-ipfs',
    'enclave/crates/skw-metadata',
    'enclave/crates/skw-types',
    'enclave/crates/skw-unit-test',
    'enclave/crates/skw-utils',
    'mock-enclave/src/skw-vm-primitives',
    'mock-enclave/src/skw-vm-host',
    'mock-enclave/src/skw-vm-engine',
    'mock-enclave/src/skw-vm-engine-cli',
    'mock-enclave/src/near-test-contracts',
    'skw-contract-sdk/skw-contract-sdk',
    'skw-contract-sdk/skw-sdk-macros',
    'skw-contract-sdk/skw-sdk-sim',
    'skw-contract-sdk/near-contract-standards',
    'skw-contract-sdk/sys',
    'skw-contract-sdk/examples/',
]
[profile.release]
panic = 'unwind'
