[workspace]
members = [
    # blockchain 
    'crates/skw-blockchain-node',
    'crates/skw-blockchain-pallets/pallet-naming',
    'crates/skw-blockchain-pallets/pallet-secrets',
    'crates/skw-blockchain-pallets/pallet-s-contract',
    'crates/skw-blockchain-pallets/pallet-registry',
    'crates/skw-blockchain-runtime',

    # SkyeKiwi VM based on NEAR VM
    'crates/skw-vm-primitives',
    'crates/skw-vm-host',
    'crates/skw-vm-engine',
    'crates/skw-vm-engine-cli',
    'crates/near-test-contracts',

    # SkyeKiwi VM contract sdk based on near-sdk-rs
    'crates/skw-contract-sdk',
    'crates/skw-contract-macros',
    'crates/skw-contract-sys',
]

exclude = [
    'enclave/app',
    'enclave/enclave',
    'skw-contract-sdk/examples/',
    'teaclave-sgx-sdk',

    # unfinished crates
    'crates/skw-vm-runtime',
    'crates/skw-vm-store',
    'crates/skw-contract-sim',
    'crates/near-contract-standards',

    # SkyeKiwi Protocol in Intel SGX enclave  
    'crates/skw-sgx-crypto',
    'crates/skw-sgx-driver',
    'crates/skw-sgx-file',
    'crates/skw-sgx-ipfs',
    'crates/skw-sgx-metadata',
    'crates/skw-sgx-types',
    'crates/skw-sgx-unit-test',
    'crates/skw-sgx-utils',

    "teaclave-sgx-sdk/"
]
[profile.release]
panic = 'unwind'
