[package]
authors = ['SkyeKiwi <https://github.com/skyekiwi>']
description = 'offchain vm account sycner'
edition = '2021'
homepage = 'https://skye.kiwi'
license = 'GPL-3.0'
name = 'pallet-s-account'
readme = 'README.md'
repository = 'https://github.com/skyekiwi/skyekiwi-network'
version = '3.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
bs58 = { version = "0.4.0", default-features = false}
skw-blockchain-primitives = { path = "../primitives", default-features = false }
pallet-secrets = { default-features = false, path = "../pallet-secrets" }
pallet-s-contract = { default-features = false, path = "../pallet-s-contract" }
pallet-parentchain = { default-features = false, path = "../pallet-parentchain" }
pallet-treasury= { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30"}
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.0.1", default-features = false, features = ["derive"] }
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30"}
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
frame-benchmarking = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30", optional = true }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }

[dev-dependencies]
pallet-balances= { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30"} 
pallet-treasury= { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30"}
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
sp-io = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
pallet-preimage = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" } 

[features]
default = ['std']
runtime-benchmarks = [
    'frame-benchmarking/runtime-benchmarks',
    'frame-support/runtime-benchmarks',
    'frame-system/runtime-benchmarks',
]
std = [
	"codec/std",
    "sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
]
try-runtime = ['frame-support/try-runtime']