[package]
name = "skw-sdk-sim"
version = '0.1.0'
authors = ['SkyeKiwi <hello@skye.kiwi>', "Near Inc <max@nearprotocol.com>"]
edition = '2021'
homepage = 'https://skye.kiwi'
repository = 'https://github.com/skyekiwi/skyekiwi-network'
license = 'GPL-3.0'
readme = 'README.md'
description = """
NEAR Simulator & cross-contract testing library
"""


[dependencies]
skw-contract-sdk = { path = "../skw-contract-sdk" }
near-crypto = "=0.1.0"
near-primitives = "=0.1.0-pre.1"
near-vm-logic = "=4.0.0-pre.1"

near-pool = "=0.1.0-pre.1"
near-store = "=0.1.0-pre.1"
near-runtime = "=4.0.0-pre.1"

lazy-static-include = "3"
# Temporary workaround see https://github.com/bitvecto-rs/bitvec/issues/105
funty = "=1.1.0"

[dev-dependencies]
quickcheck = "0.9"
quickcheck_macros = "0.9"
fungible-token = { path="../examples/fungible-token/ft" }

[features]
default = []
no_cache = ["near-store/no_cache", "near-runtime/no_cache"]
no_sim = []
no_contract_cache = []
