[package]
name = "skw_utils"
version = "0.1.0"
edition = "2018"

[dependencies]
skw_types =  { path = "../skw-sgx-types" }
sgx_tstd = { path = "../../teaclave-sgx-sdk/sgx_tstd" }

[dev-dependencies]


[features]
default = []

