[package]
name = "skw_utils"
version = "0.1.0"
edition = "2018"

[dependencies]
skw_types =  { path = "../skw-sgx-types" }
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk" }

[dev-dependencies]


[features]
default = []

