[package]
name = "near-vm-runner"
version = "0.0.0"
authors = ["SkyeKiwi <hello@skye.kiwi>","Near Inc <hello@nearprotocol.com>"]
publish = false
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
categories = ["wasm"]
repository = "https://github.com/nearprotocol/nearcore"
homepage = "https://github.com/nearprotocol/nearcore"
description = """
This crate implements the specification of the interface that Near blockchain exposes to the smart contracts.
"""

[dependencies]
borsh = "0.9"
serde = { version = "1", features = ["derive"] }
wasmer-runtime = { version = "0.18.0", features = ["default-backend-singlepass"], default-features = false, package = "wasmer-runtime-near", optional = true }
wasmer-runtime-core = { version = "0.18.2", package = "wasmer-runtime-core-near", optional = true}
wasmparser = "0.78"
memoffset = "0.6"

# Use the following for development versions of Wasmer.
# wasmer = { package = "wasmer-near", git = "https://github.com/near/wasmer", branch = "near-main", optional = true, default-features = false, features = ["singlepass", "universal"] }
# wasmer-types = { package = "wasmer-types-near", git = "https://github.com/near/wasmer", branch = "near-main", optional = true }
# wasmer-compiler-singlepass = { package = "wasmer-compiler-singlepass-near", git = "https://github.com/near/wasmer", branch = "near-main", optional = true }
# wasmer-engine-universal = { package = "wasmer-engine-universal-near", git = "https://github.com/near/wasmer", branch = "near-main", optional = true }
# wasmer-vm = { package = "wasmer-vm-near", git = "https://github.com/near/wasmer", branch = "near-main" }
wasmer = { package = "wasmer-near", version = "=2.0.3", optional = true, default-features = false, features = ["singlepass", "universal"] }
wasmer-types = { package = "wasmer-types-near", version = "=2.0.3", optional = true }
wasmer-compiler-singlepass = { package = "wasmer-compiler-singlepass-near", version = "=2.0.3", optional = true }
wasmer-engine-universal = { package = "wasmer-engine-universal-near", version = "=2.0.3", optional = true }
wasmer-vm = { package = "wasmer-vm-near", version = "=2.0.3" }

pwasm-utils = "0.12"
parity-wasm = "0.41"
anyhow = { version = "1.0.19", optional = true }
near-vm-logic = { path = "../near-vm-logic", default-features = false, features = [] }
near-vm-errors = { path = "../near-vm-errors" }
near-primitives = { git = "https://github.com/near/nearcore" }
near-stable-hasher = { git = "https://github.com/near/nearcore" }
cached = "0.23.0"
tracing = { version = "0.1", default-features = false }
threadpool = "1.8.1"

[dev-dependencies]
near-test-contracts = { git = "https://github.com/near/nearcore" }
assert_matches = "1.3"
wat = "1.0.40"
base64 = "0.13"

[features]
# all vms enabled for now
default = ["wasmer2_vm"]
wasmer2_vm = [ "wasmer", "wasmer-types", "wasmer-compiler-singlepass",  "wasmer-engine-universal", ]
no_cpu_compatibility_checks = []

no_cache = []
nightly_protocol = ["near-primitives/nightly_protocol"]

[package.metadata.cargo-udeps.ignore]
# `no_cache` feature leads to an unused `cached` crate
normal = ["cached"]
