[package]
name = "skw_types"
version = "0.1.0"
edition = "2018"

[dependencies]
sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }

[patch.'https://github.com/apache/teaclave-sgx-sdk.git']
sgx_tstd = { path = "../../../teaclave-sgx-sdk/sgx_tstd" }

[features]
default = ["std"]
std = []
