[package]
name = "cross-contract-high-level"
version = "0.1.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
skw-contract-sdk = { path = "../../" }

[dev-dependencies]
skw-vm-interface = { path = "../../../skw-vm-interface" }
skw-vm-primitives = { path = "../../../skw-vm-primitives" }


[profile.release]
codegen-units = 1
# Tell `rustc` to optimize for small code size.
opt-level = "z"
lto = true
debug = false
panic = "abort"

[workspace]
members = []
