[package]
name = "non-fungible-token-wrapper"
version = "0.0.2"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2018"

[dev-dependencies]
skw-contract-sdk = { path = "../../" }
skw-sdk-sim = { path = "../../../skw-contract-sim" }
near-contract-standards = { path = "../../near-contract-standards" }

# remember to include a line for each contract
non-fungible-token = { path = "./nft" }
approval-receiver = { path = "./test-approval-receiver" }
token-receiver = { path = "./test-token-receiver" }

[profile.release]
codegen-units = 1
# Tell `rustc` to optimize for small code size.
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true

[workspace]
# remember to include a member for each contract
members = [
  "nft",
  "test-approval-receiver",
  "test-token-receiver",
]

