[package]
name = "skw_unit_test"
version = "0.1.0"
edition = "2018"

[dependencies]
skw_file =  { path = "../skw-file" }
skw_crypto =  { path = "../skw-crypto" }
skw_metadata =  { path = "../skw-metadata" }
skw_utils = { path = "../skw-utils" }
skw_types = { path = "../skw-types" }
sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tunittest = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_rand = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }

[features]
default = []

[patch.'https://github.com/apache/teaclave-sgx-sdk.git']
sgx_tstd = { path = "../../../teaclave-sgx-sdk/sgx_tstd" }
sgx_tunittest = { path = "../../../teaclave-sgx-sdk/sgx_tunittest" }
sgx_rand = { path = "../../../teaclave-sgx-sdk/sgx_rand" }
