[package]
name = "non-fungible-token"
version = "1.1.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
skw-contract-sdk = { path = "../../skw-contract-sdk" }
near-contract-standards = { path = "../../../near-contract-standards" }
