name: Check Set-Up & Build

on:
  push:
    branches: [ master ]
  pull_request:

  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set-Up
        run: 
          sudo apt install -y cmake pkg-config libssl-dev git build-essential clang libclang-dev curl


      - name: Install Rustup
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source ~/.cargo/env
          rustup default stable
          rustup update nightly
          rustup update stable
          rustup target add wasm32-unknown-unknown --toolchain nightly

      # - name: Check Build
      #   run: |
      #     yarn blockchain:ci

      - name: Check Smart Contract Compile
        run: |
          yarn contract:compile
      
      - name: Check enclave Compile
        run: |
          yarn enclave:sim
          make
          cd bin && ./app
          exit

