[package]
authors = ['SkyeKiwi <https://github.com/skyekiwi>']
description = 'blockchain primitives for the SkyeKiwi Network'
edition = '2021'
homepage = 'https://skye.kiwi'
license = 'GPL-3.0'
name = 'skw-blockchain-primitives'
readme = 'README.md'
repository = 'https://github.com/skyekiwi/skyekiwi-network'
version = '3.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
borsh = { default-features = false, version =  '0.9'}
ed25519-dalek = { version = "1.0.1", default-features = false, features = ["u64_backend"]}

[features]
default = ['std']
std = [
    'sp-std/std',
    'borsh/std'
]
