[package]
authors = ['SkyeKiwi <https://github.com/skyekiwi>']
description = 'blockchain primitives for the SkyeKiwi Network'
edition = '2021'
homepage = 'https://skye.kiwi'
license = 'GPL-3.0'
name = 'skw-blockchain-primitives'
readme = 'README.md'
repository = 'https://github.com/skyekiwi/skyekiwi-network'
version = '3.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dev-dependencies]
test-env-log = "0.2.7"
log = "*"
env_logger="*"

[dependencies]
sp-std = { default-features = false, git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-12', version = '4.0.0-dev'}
borsh = { default-features = false, version =  '0.9'}

[features]
default = ['std']
std = [
]
