[package]
name = "skw-vm-primitives"
version = "0.1.0"
authors = ["SkyeKiwi <hello@skye.kiwi>"]
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
categories = ["wasm"]
repository = "https://github.com/skyekiwi/skyekiwi-network"
homepage = "https://github.com/skyekiwi/skyekiwi-network"
description = """
Primitives types for the SkyeKiwi Network Secret Contracts
"""

[dependencies]
base64 = "0.11"
bs58 = "0.4"
sha2 = "0.9"
num-rational = { version = "0.3.1", default-features = false }
wasmi = { git = "https://github.com/paritytech/wasmi", features = ['v1'] }
serde = { version = "1", features = ["derive", "rc"], optional = true }
borsh = { version = "0.9", features = ["rc"], optional = true }
near-crypto = { git = "https://github.com/near/nearcore" }
smart-default = "0.6"

[dev-dependencies]
serde_json = "1"

[features]
default = ["std", "serde", "borsh"]
std = [
  "sha2/std",
  "num-rational/std",
  "serde/std",
]
